apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-functions
  namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
spec:
  interval: 30m
  dependsOn:
    - name: crossplane-deployment
      namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
  chart:
    spec:
      chart: sthings-cluster
      version: 0.3.20
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
      interval: 12h
  values:
    installCRDs: true
    customresources:
      functionAutoReady:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: Function
        metadata:
          name: function-auto-ready
        spec:
          package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.6.0
      functionGoTemplating:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: Function
        metadata:
          name: function-go-templating
        spec:
          package: xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.11.3
      functionKCL:
        apiVersion: pkg.crossplane.io/v1
        kind: Function
        metadata:
          name: function-kcl
        spec:
          package: xpkg.upbound.io/crossplane-contrib/function-kcl:v0.12.0
      functionPatchAndTransform:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: Function
        metadata:
          name: function-patch-and-transform
        spec:
          package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.9.3
