---
# this file needs to be reworked and is not selected at tem moment in kustomization.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-configuration
  namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
spec:
  interval: 30m
  dependsOn:
    - name: crossplane-deployment
      namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
  chart:
    spec:
      chart: sthings-cluster
      version: 0.3.20
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
      interval: 12h
  values:
    installCRDs: true
    customresources:
      deploymentTemplate:
        apiVersion: pkg.crossplane.io/v1beta1
        kind: DeploymentRuntimeConfig
        metadata:
          name: ${CROSSPLANE_TERRAFORM_CONFIG_NAME:-terraform-runtime-config}
          namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
        spec:
          deploymentTemplate:
            spec:
              selector: {}
              strategy: {}
              template:
                spec:
                  containers:
                  - envFrom:
                    - secretRef:
                        name: ${CROSSPLANE_TERRAFORM_S3_SECRET_NAME:-terraform-s3}
                    name: package-runtime
                    image: ${CROSSPLANE_TERRAFORM_PROVIDER_IMAGE:-ghcr.io/stuttgart-things/sthings-cptf:1.14.3}
                    args:
                      - -d
                      - --poll=${CROSSPLANE_TERRAFORM_POLL:-30s}
                      - --max-reconcile-rate=${CROSSPLANE_TERRAFORM_RECONCILE_RATE:-10}
                    resources: {}
      provider:
        apiVersion: pkg.crossplane.io/v1
        kind: Provider
        metadata:
          name: provider-terraform
          namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
        spec:
          package: xpkg.upbound.io/upbound/provider-terraform:${CROSSPLANE_TERRAFORM_PROVIDER_VERSION:-v1.0.5}
          runtimeConfigRef:
            name: ${CROSSPLANE_TERRAFORM_CONFIG_NAME:-terraform-runtime-config}
