---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-deployment
  namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
spec:
  interval: 30m
  chart:
    spec:
      chart: crossplane
      version: ${CROSSPLANE_VERSION:-2.1.3}
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: ${CROSSPLANE_NAMESPACE:-crossplane-system}
      interval: 12h
  values:
    args:
      - '--debug'
      - '--enable-usages'
    provider:
      packages:
        - xpkg.upbound.io/crossplane-contrib/provider-helm:${CROSSPLANE_HELM_PROVIDER_VERSION:-v1.0.6}
        - xpkg.upbound.io/crossplane-contrib/provider-kubernetes:${CROSSPLANE_K8S_PROVIDER_VERSION:-v1.2.0}
