---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${TEKTON_NAME:-tekton-pipelines}
  namespace: ${TEKTON_NAMESPACE:-tekton-pipelines}
spec:
  interval: 30m
  chart:
    spec:
      chart: tekton
      version: ${TEKTON_VERSION:-0.76.0}
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${TEKTON_NAMESPACE:-tekton-pipelines}
      interval: 12h