---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: ${METALLB_NAMESPACE:-metallb-system}
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: ${METALLB_CHART_VERSION:=6.4.2}
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ${METALLB_NAMESPACE:-metallb-system}
      interval: 12h
  values:
    installCRDs: ${METALLB_INSTALL_CRDS:=true}
