---
apiVersion: v1
kind: Namespace
metadata:
  name: ${METALLB_NAMESPACE:-metallb-system}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: ${METALLB_NAMESPACE:-metallb-system}
spec:
  type: oci
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stuttgart-things
  namespace: ${METALLB_NAMESPACE:-metallb-system}
spec:
  type: oci
  interval: 1h
  url: oci://ghcri.io/stuttgart-things
