---
apiVersion: v1
kind: Namespace
metadata:
  name: ${DAPR_CBW_NAMESPACE:-cluster-build-watch}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/${FLUX_SOURCE_API_VERSION:-v1}
kind: OCIRepository
metadata:
  name: dapr-cluster-build-watch-kustomize
  namespace: ${DAPR_CBW_NAMESPACE:-cluster-build-watch}
spec:
  interval: 1h
  url: oci://ghcr.io/stuttgart-things/dapr-cluster-build-watch-kustomize
  ref:
    tag: ${DAPR_CBW_VERSION:-2338624484dd}
