---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: ${CILIUM_NAMESPACE:-kube-system}
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: ${CILIUM_CHART_VERSION:-1.18.5}
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: ${CILIUM_NAMESPACE:-kube-system}
      interval: 12h
  values:
    kubeProxyReplacement: ${CILIUM_KUBE_PROXY_REPLACEMENT:-true}
    k8sServiceHost: ${CILIUM_API_SERVER_HOST}
    k8sServicePort: ${CILIUM_API_SERVER_PORT:-6443}
    operator:
      replicas: ${CILIUM_OPERATOR_REPLICAS:-1}
    gatewayAPI:
      enabled: ${CILIUM_GATEWAY_API_ENABLED:-true}
    l2announcements:
      enabled: ${CILIUM_L2_ANNOUNCEMENTS_ENABLED:-true}
    externalIPs:
      enabled: ${CILIUM_EXTERNAL_IPS_ENABLED:-true}
