---
apiVersion: v1
kind: Namespace
metadata:
  name: ${CILIUM_NAMESPACE:-kube-system}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: ${CILIUM_NAMESPACE:-kube-system}
spec:
  interval: 24h
  url: https://helm.cilium.io
