---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-pve-exporter
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus-pve-exporter
  ports:
    - name: http
      port: 9221
      targetPort: http
      protocol: TCP
