---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - components/redis-stack
  - components/omni-pitcher
  - components/core-catcher
  - components/k8s-pitcher
  - components/scout
  - components/light-catcher
  - components/wled-mock
  - components/demo-pitcher
