---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - components/redis-stack
  - components/omni-pitcher
  - components/core-catcher
  - components/k8s-pitcher
  - components/scout
  - components/light-catcher
  - components/wled-mock
  - components/demo-pitcher
  - components/led-catcher
  - components/git-pitcher
  - components/redis-stack/sops
  - components/omni-pitcher/sops
  - components/core-catcher/sops
  - components/scout/sops
  - components/light-catcher/sops
  - components/demo-pitcher/sops
  - components/led-catcher/sops
  - components/omni-pitcher/route
  - components/core-catcher/route
  - components/scout/route
  - components/led-catcher/route
  - components/light-catcher/route
  - components/wled-mock/route
  - components/demo-pitcher/route
