---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: ${OPENLDAP_NAMESPACE:-openldap}
spec:
  interval: 30m
  chart:
    spec:
      chart: openldap
      version: ${OPENLDAP_VERSION:-24.4.9}
      sourceRef:
        kind: HelmRepository
        name: openldap
        namespace: ${OPENLDAP_NAMESPACE:-openldap}
      interval: 12h
  values:
    replicaCount: "${REPLICAS:-1}"
    global:
      adminUser: ${ADMIN_USER:-admin}
      adminPassword: ${ADMIN_PASSWORD}
      configUser: ${ADMIN_USER:-admin}
      configPassword: ${ADMIN_PASSWORD}
    logLevel: debug
    service:
      enableLdapPort: ${ENABLE_LDAP_PORT:-true}
      enableSslLdapPort: ${ENABLE_LDAPS_PORT:-false}
      type: ${SERVICE_TYPE:-ClusterIP}
    replication:
      enabled: ${REPLICATION_ENABLED:-false}
    persistence:
      enabled: ${PERSISTENCE_ENABLED:-true}
      size: ${STORAGE_SIZE:-8Gi}
      storageClass: ${STORAGE_CLASS}
    test:
      enabled: ${TEST_ENABLED:-false}
    ltb-passwd:
      enabled : ${LTB_PASSWD_ENABLED:-false}
    phpldapadmin:
      enabled: ${PHP_ADMIN_ENABLED:-false}