apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd-mgmt-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Apps deployed to the cicd-mgmt-1 kind cluster

  sourceRepos:
    - 'https://github.com/stuttgart-things/*'
    - 'oci://ghcr.io/stuttgart-things/*'
    - 'https://github.com/stefanprodan/podinfo'

  destinations:
    - name: cicd-mgmt-1
      namespace: '*'
    - name: in-cluster
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
