---
apiVersion: v1
kind: Namespace
metadata:
  name: ${VAULT_NAMESPACE:-vault}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: unseal
  namespace: ${VAULT_NAMESPACE:-vault}
spec:
  interval: 1h
  url: ${UNSEAL_HELM_REPO_URL:-https://pytoshka.github.io/vault-autounseal}
