---
version: 3
vars:
  PROJECT:
    sh: echo ${PROJECT}
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD); else echo main ; fi
  CROSSPLANE_PACKAGE_REGISTRY: ghcr.io
  DAGGER_CROSSPLANE_MODULE: github.com/stuttgart-things/dagger/crossplane
  DAGGER_CROSSPLANE_MODULE_VERSION: v0.0.2

includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml


tasks:
  get-variables:
    desc: Get variables from app folder
    cmds:
      - |
        # INPUT FOLDER CONTAINING YAML FILES
        echo "Enter app folder path (e.g. apps/app-xy):"
        read APP_FOLDER;

        output_file="/tmp/variables.yaml"

        # CLEAR THE OUTPUT FILE
        > "$output_file"

        # ITERATE OVER ALL YAML FILES IN THE FOLDER
        find "${APP_FOLDER}" -type f -name "*.yaml" | while read -r file; do
            echo "Processing: $file..."

            # EXTRACT VARIABLES WITH DEFAULT VALUES FROM EACH YAML FILE
            grep -oP '\$\{([A-Z0-9_]+)(?::-([^\}]+))?\}' "$file" | sort | uniq | while read -r line; do

                # EXTRACT VARIABLE NAME AND DEFAULT VALUE
                var_name=$(echo "$line" | grep -oP '\$\{\K[A-Z0-9_]+')
                default_value=$(echo "$line" | grep -oP ':-\K[^}]+' || echo "")

                # WRITE TO THE OUTPUT IN YAML FORMAT (APPEND ONLY IF NOT ALREADY PRESENT)
                if ! grep -q "^$var_name:" "$output_file"; then
                    if [ -n "$default_value" ]; then
                        echo "$var_name: $default_value" >> "$output_file"
                    else
                        echo "$var_name: " >> "$output_file"
                    fi
                fi
            done
        done

        # Display the generated YAML
        cat "$output_file"

  release:
    deps:
      - check
    desc: push new version
    cmds:
      - task: pr
      - npx semantic-release --dry-run
      - npx semantic-release --debug --no-ci
      - echo released version $(git describe --tags --abbrev=0)

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
