---
apiVersion: v1
kind: Namespace
metadata:
  name: ${FLUX_WEB_NAMESPACE:-flux-system}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: ${FLUX_WEB_NAMESPACE:-flux-system}
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts
