apiVersion: v1
kind: Secret
metadata:
  name: avp-demo-secret
  annotations:
    avp.kubernetes.io/path: "apps/data/test"
type: Opaque
stringData:
  username: <username>
  password: <password>
  api_key: <api_key>
