---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-stack-auth
  namespace: ${HOMERUN2_NAMESPACE:-homerun2}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${HOMERUN2_SECRET_STORE:-set-HOMERUN2_SECRET_STORE}
  target:
    name: redis-stack-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: ${HOMERUN2_SECRET_PATH:-homerun2}
        property: redis-password
