---
apiVersion: v1
kind: Secret
metadata:
  name: homerun2-light-catcher-redis
  namespace: ${HOMERUN2_LIGHT_CATCHER_TABLETENNIS_NAMESPACE:-homerun2-tabletennis}
type: Opaque
data:
  password: ${HOMERUN2_REDIS_PASSWORD_B64}
