---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak-certificate-configuration
  namespace: ${KEYCLOAK_NAMESPACE:-keycloak}
spec:
  interval: 30m
  chart:
    spec:
      chart: sthings-cluster
      version: 0.3.15
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${KEYCLOAK_NAMESPACE:-keycloak}
      interval: 12h
  values:
    customresources:
      ingress-certificate-console:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: keycloak-ingress
          namespace: ${KEYCLOAK_NAMESPACE:-keycloak}
        spec:
          commonName: ${INGRESS_HOSTNAME:-keycloak}.${INGRESS_DOMAIN}
          dnsNames:
          - ${INGRESS_HOSTNAME:-keycloak}.${INGRESS_DOMAIN}
          issuerRef:
            name: ${CLUSTER_ISSUER}
            kind: ClusterIssuer
          secretName: ${INGRESS_HOSTNAME:-keycloak}.${INGRESS_DOMAIN}-tls
