---
apiVersion: v1
kind: Namespace
metadata:
  name: ${KEYCLOAK_NAMESPACE:-keycloak}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: ${KEYCLOAK_NAMESPACE:-keycloak}
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stuttgart-things
  namespace: ${KEYCLOAK_NAMESPACE:-keycloak}
spec:
  type: oci
  interval: 1h
  url: oci://ghcri.io/stuttgart-things
