---
apiVersion: v1
kind: Namespace
metadata:
  name: ${CLUSTERBOOK_NAMESPACE:-clusterbook}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clusterbook
  namespace: ${CLUSTERBOOK_NAMESPACE:-clusterbook}
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/stuttgart-things/clusterbook
