---
apiVersion: v1
kind: Namespace
metadata:
  name: ${CLUSTERBOOK_NAMESPACE:-clusterbook}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/${FLUX_SOURCE_API_VERSION:-v1}
kind: OCIRepository
metadata:
  name: clusterbook-kustomize
  namespace: ${CLUSTERBOOK_NAMESPACE:-clusterbook}
spec:
  interval: 1h
  url: oci://ghcr.io/stuttgart-things/clusterbook-kustomize
  ref:
    tag: ${CLUSTERBOOK_VERSION:-1.21.3}
