---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homerun2-wled-mock
  namespace: ${HOMERUN2_NAMESPACE:-homerun2}
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: homerun2-wled-mock-kustomize
  prune: true
  wait: true
  targetNamespace: ${HOMERUN2_NAMESPACE:-homerun2}
  patches:
    # Override the container image tag
    - target:
        kind: Deployment
        name: homerun2-wled-mock
      patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: homerun2-wled-mock
        spec:
          template:
            spec:
              containers:
                - name: homerun2-wled-mock
                  image: ghcr.io/stuttgart-things/homerun2-wled-mock:${HOMERUN2_WLED_MOCK_VERSION:-v0.3.0}
