---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/redis-stack
  - ../../components/omni-pitcher
  - ../../components/core-catcher
  - ../../components/notification-catcher
  - ../../components/scout
  - ../../components/redis-stack/sops
  - ../../components/omni-pitcher/sops
  - ../../components/core-catcher/sops
  - ../../components/scout/sops
  - ../../components/omni-pitcher/route
  - ../../components/core-catcher/route
  - ../../components/scout/route
