---
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: ${TEKTON_TARGET_NAMESPACE:-tekton-pipelines}
  profile: ${TEKTON_PROFILE:-all}
  pipeline:
    enable-api-fields: ${TEKTON_ENABLE_API_FIELDS:-beta}
    disable-inline-spec: ${TEKTON_DISABLE_INLINE_SPEC:-""}
    default-image-pull-policy: ${TEKTON_IMAGE_PULL_POLICY:-Always}
  pruner:
    disabled: ${TEKTON_PRUNER_DISABLED:-false}
    schedule: ${TEKTON_PRUNER_SCHEDULE:-"0 8 * * *"}
    resources:
      - taskrun
      - pipelinerun
    keep: ${TEKTON_PRUNER_KEEP:-100}
    keep-since: ${TEKTON_PRUNER_KEEP_SINCE:-1440}
