---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${EXTRA_CERT_NAME}
  namespace: ${EXTRA_CERT_NAMESPACE:-default}
spec:
  secretName: ${EXTRA_CERT_SECRET_NAME}
  issuerRef:
    name: ${EXTRA_CERT_ISSUER:-vault-pki}
    kind: ${EXTRA_CERT_ISSUER_KIND:-ClusterIssuer}
  commonName: '*.${EXTRA_CERT_DOMAIN}'
  dnsNames:
    - '*.${EXTRA_CERT_DOMAIN}'
  duration: 2160h
  renewBefore: 360h
