---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
  namespace: ${VAULT_NAMESPACE:-vault}
spec:
  parentRefs:
    - name: ${GATEWAY_NAME:-cilium-gateway}
      namespace: ${GATEWAY_NAMESPACE:-default}
  hostnames:
    - "${VAULT_HOSTNAME}.${VAULT_DOMAIN}"
  rules:
    - backendRefs:
        - name: vault
          port: 8200
