---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: ${VAULT_NAMESPACE:-vault}
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/vault/vault
      version: ${VAULT_VERSION:-1.9.0}
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${VAULT_NAMESPACE:-vault}
      interval: 12h
  values:
    global:
      storageClass: ${STORAGE_CLASS:-local-path}
      security:
        allowInsecureImages: true

    server:
      dev:
        enabled: ${VAULT_DEV_MODE:-true}
        devRootToken: ${VAULT_DEV_ROOT_TOKEN:-root}
      ingress:
        enabled: false

    injector:
      enabled: ${INJECTOR_ENABLED:-false}

    volumePermissions:
      enabled: ${ENABLE_VOLUME_PERMISSIONS:-true}
      image:
        registry: ${REGISTRY:-ghcr.io}
        repository: ${OS_SHELL_REPOSITORY:-stuttgart-things/os-shell}
        tag: ${OS_SHELL_TAG:-12-debian-12-r50}
        pullPolicy: ${OS_SHELL_PULL_POLICY:-IfNotPresent}
