---
apiVersion: v1
kind: Namespace
metadata:
  name: ${UPTIME_KUMA_NAMESPACE:-uptime-kuma}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: ${UPTIME_KUMA_NAMESPACE:-uptime-kuma}
spec:
  interval: 1h
  url: https://dirsigler.github.io/uptime-kuma-helm
