---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ${INGRESS_NGINX_NAMESPACE:-ingress-nginx}
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: ${INGRESS_NGINX_CHART_VERSION:=4.12.0}
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ${INGRESS_NGINX_NAMESPACE:-ingress-nginx}
      interval: 12h
  values:
    installCRDs: true