---
apiVersion: v1
kind: Namespace
metadata:
  name: ${MACHINERY_REGISTRY_API_NAMESPACE:-machinery-registry}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/${FLUX_SOURCE_API_VERSION:-v1}
kind: OCIRepository
metadata:
  name: machinery-registry-api-kustomize
  namespace: ${MACHINERY_REGISTRY_API_NAMESPACE:-machinery-registry}
spec:
  interval: 1h
  url: oci://ghcr.io/stuttgart-things/machinery-registry-api-kustomize
  ref:
    tag: ${MACHINERY_REGISTRY_API_VERSION:-v1.0.0}
