---
apiVersion: v1
kind: Namespace
metadata:
  name: ${OPENBAO_NAMESPACE:-openbao}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: ${OPENBAO_NAMESPACE:-openbao}
spec:
  interval: 24h
  url: https://openbao.github.io/openbao-helm
