---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: ${NAMESPACE:-openebs}
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: ${VERSION:-4.2.0}
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: ${NAMESPACE:-openebs}
      interval: 12h
  values:
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: ${VOLUMESNAPSHOTS_ENABLED:-false}
    mayastor:
      csi:
        node:
          initContainers:
            enabled: ${CSI_NODE_INIT_CONTAINERS_ENABLED:-false}
    engines:
      local:
        lvm:
          enabled: ${LOCAL_LVM_ENABLED:-false}
        zfs:
          enabled: ${LOCAL_ZFS_ENABLED:-false}
      replicated:
        mayastor:
          enabled: ${REPLICATED_MAYASTOR_ENABLED:-false}
