---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homerun2-scout-token
  namespace: ${HOMERUN2_NAMESPACE:-homerun2}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${HOMERUN2_SECRET_STORE:-set-HOMERUN2_SECRET_STORE}
  target:
    name: homerun2-scout-token
    creationPolicy: Owner
  data:
    - secretKey: auth-token
      remoteRef:
        key: ${HOMERUN2_SECRET_PATH:-homerun2}
        property: scout-auth-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homerun2-scout-redis
  namespace: ${HOMERUN2_NAMESPACE:-homerun2}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${HOMERUN2_SECRET_STORE:-set-HOMERUN2_SECRET_STORE}
  target:
    name: homerun2-scout-redis
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: ${HOMERUN2_SECRET_PATH:-homerun2}
        property: redis-password
