---
apiVersion: v1
kind: Namespace
metadata:
  name: ${HARBOR_NAMESPACE:-harbor}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: ${HARBOR_NAMESPACE:-harbor}
spec:
  type: default
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stuttgart-things
  namespace: ${HARBOR_NAMESPACE:-harbor}
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/stuttgart-things
