---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homerun-redis-stack
  namespace: ${HOMERUN_NAMESPACE:-homerun}
spec:
  interval: 30m
  chart:
    spec:
      chart: homerun
      version: ${HOMERUN_VERSION:-v0.2.1}
      sourceRef:
        kind: HelmRepository
        name: homerun
        namespace: ${HOMERUN_NAMESPACE:-homerun}
      interval: 12h
  values:
    redis-stack:
      enabled: ${REDIS_STORAGE_ENABLED:true}
      sentinel:
        service:
          type: ${REDIS_SERVICE_TYPE:-ClusterIP}
      global:
        redis:
          password: ${REDIS_PASSWORD}
      master:
        service:
          type: ${REDIS_SERVICE_TYPE:-ClusterIP}
        persistence:
          enabled: ${REDIS_STORAGE_ENABLED:true}
          storageClass: ${REDIS_STORAGE_CLASS}
          size: ${REDIS_STORAGE_SIZE:8Gi}
      replica:
        persistence:
          enabled: ${REDIS_STORAGE_ENABLED:true}
          storageClass: ${REDIS_STORAGE_CLASS}
          size: ${REDIS_STORAGE_SIZE:8Gi}
