---
apiVersion: source.toolkit.fluxcd.io/${FLUX_SOURCE_API_VERSION:-v1}
kind: OCIRepository
metadata:
  name: homerun2-core-catcher-kustomize
  namespace: ${HOMERUN2_NAMESPACE:-homerun2}
spec:
  interval: 1h
  url: oci://ghcr.io/stuttgart-things/homerun2-core-catcher-kustomize
  ref:
    tag: ${HOMERUN2_CORE_CATCHER_VERSION:-v0.5.0}
