---
apiVersion: v1
kind: Namespace
metadata:
  name: ${CLAIM_MACHINERY_API_NAMESPACE:-claim-machinery}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: claim-machinery-api-kustomize
  namespace: ${CLAIM_MACHINERY_API_NAMESPACE:-claim-machinery}
spec:
  interval: 1h
  url: oci://ghcr.io/stuttgart-things/claim-machinery-api-kustomize
  ref:
    tag: ${CLAIM_MACHINERY_API_VERSION:-v0.5.6}
