---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-deployment
  namespace: ${MINIO_NAMESPACE:-minio}
spec:
  dependsOn:
    - name: minio-certificate-configuration
      namespace: ${MINIO_NAMESPACE:-minio}
  interval: 30m
  chart:
    spec:
      chart: minio
      version: ${MINIO_VERSION:-14.8.0}
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ${MINIO_NAMESPACE:-minio}
      interval: 12h
  values:
    image:
      registry: ghcr.io
      repository: stuttgart-things/sthings-minio
      tag: 2024.10.13
    networkPolicy:
      enabled: true
      allowExternal: true
    auth:
      rootUser: ${MINIO_ADMIN_USER}
      rootPassword: ${MINIO_ADMIN_PASSWORD}
    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 500m
      extraTls:
        - hosts:
            - ${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}
          secretName: ${INGRESS_HOSTNAME_CONSOLE}-ingress-tls
      hostname: ${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}
    apiIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 500m
      tls: true
      extraTls:
        - hosts:
            - ${INGRESS_HOSTNAME_API}.${INGRESS_DOMAIN}
          secretName: ${INGRESS_HOSTNAME_API}-ingress-tls
      hostname: ${INGRESS_HOSTNAME_API}.${INGRESS_DOMAIN}
    persistence:
      enabled: true
      storageClass: ${STORAGE_CLASS:-longhorn}
    extraEnvVars:
      - name: MINIO_SERVER_URL
        value: https://${INGRESS_HOSTNAME_API}.${INGRESS_DOMAIN}
      - name: MINIO_BROWSER_REDIRECT_URL
        value: https://${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}:9001
      - name: MINIO_IDENTITY_OPENID_CONFIG_URL
        value: https://keycloak.fluxdev-3.sthings-vsphere.labul.sva.de/realms/master/.well-known/openid-configuration
      - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
        value: https://${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}/oauth_callback
      - name: MINIO_IDENTITY_OPENID_CLIENT_ID
        value: minio
      - name: MINIO_IDENTITY_OPENID_SCOPES
        value: openid,profile,email,groups
      - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
        value: preferred_username #groups
      # - name: MINIO_IDENTITY_OPENID_POLICY_MAPPING
      #   value: on