---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-deployment
  namespace: ${MINIO_NAMESPACE:-minio}
spec:
  dependsOn:
    - name: minio-certificate-configuration
      namespace: ${MINIO_NAMESPACE:-minio}
  interval: 30m
  chart:
    spec:
      chart: charts/minio/minio
      version: ${MINIO_VERSION:-16.0.10}
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${MINIO_NAMESPACE:-minio}
      interval: 12h
  values:
    global:
      imageRegistry: ${MINIO_REGISTRY:-ghcr.io}
      security:
        allowInsecureImages: true
    image:
      registry: ${MINIO_REGISTRY:-ghcr.io}
      repository: ${MINIO_REPOSITORY:-stuttgart-things/minio}
      tag: ${MINIO_IMAGE_TAG:-RELEASE.2024-06-11T00-09-59Z}
    networkPolicy:
      enabled: true
      allowExternal: true
    auth:
      rootUser: ${MINIO_ADMIN_USER}
      rootPassword: ${MINIO_ADMIN_PASSWORD}
    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 500m
      extraTls:
        - hosts:
            - ${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}
          secretName: ${INGRESS_HOSTNAME_CONSOLE}-ingress-tls
      hostname: ${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}
    apiIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 500m
      tls: true
      extraTls:
        - hosts:
            - ${INGRESS_HOSTNAME_API}.${INGRESS_DOMAIN}
          secretName: ${INGRESS_HOSTNAME_API}-ingress-tls
      hostname: ${INGRESS_HOSTNAME_API}.${INGRESS_DOMAIN}
    persistence:
      enabled: true
      storageClass: ${STORAGE_CLASS:-longhorn}
    #extraEnvVarsCM: ${EXTRA_CONFIG_MAP:-minio-env-config}
    extraEnvVars:
      - name: MINIO_SERVER_URL
        value: https://${INGRESS_HOSTNAME_API}.${INGRESS_DOMAIN}
      - name: MINIO_BROWSER_REDIRECT_URL
        value: https://${INGRESS_HOSTNAME_CONSOLE}.${INGRESS_DOMAIN}:9001
