---
apiVersion: v1
kind: Namespace
metadata:
  name: ${MINIO_NAMESPACE:-minio}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stuttgart-things
  namespace: ${MINIO_NAMESPACE:-minio}
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/stuttgart-things
