---
apiVersion: v1
kind: Namespace
metadata:
  name: ${SCHMETTERPAUSE_NAMESPACE:-schmetterpause}
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: source.toolkit.fluxcd.io/${FLUX_SOURCE_API_VERSION:-v1}
kind: OCIRepository
metadata:
  name: schmetterpause-kustomize
  namespace: ${SCHMETTERPAUSE_NAMESPACE:-schmetterpause}
spec:
  interval: 1h
  url: oci://ghcr.io/stuttgart-things/schmetterpause-kustomize
  ref:
    tag: ${SCHMETTERPAUSE_VERSION:-v0.5.0}
