---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homerun-light-catcher
  namespace: ${HOMERUN_NAMESPACE:-homerun}
spec:
  interval: 30m
  chart:
    spec:
      chart: homerun
      version: ${HOMERUN_VERSION:-v0.2.0}
      sourceRef:
        kind: HelmRepository
        name: homerun
        namespace: ${HOMERUN_NAMESPACE:-homerun}
      interval: 12h
  values:
    light-catcher:
      enabled: true
      deployment:
        volumes:
          wled-config:
            volumeKind: configMap
        containers:
          homerun-light-catcher:
            volumeMounts:
              wled-config:
                mountPath: /homerun/
                volumeKind: emptyDir
      secrets:
        redis-connection-homerun-light-catcher:
          name: redis-connection-homerun-light-catcher
          labels:
            app: homerun-light-catcher
          dataType: stringData
          secretKVs:
            REDIS_SERVER: homerun-redis-stack-headless.${HOMERUN_NAMESPACE}.svc.cluster.local
            REDIS_PORT: ${REDIS_PORT:-6379}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
