---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: ${VAULT_NAMESPACE:-vault}
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/vault/vault
      version: ${vault_VERSION:-1.9.0}
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: ${VAULT_NAMESPACE:-vault}
      interval: 12h
  values:
    server:
      image:
        registry: ${REGISTRY:-ghcr.io}
        repository: ${REPOSITORY:-stuttgart-things/vault}
        tag: ${TAG:-1.20.2-debian-12-r2}
        digest: ""
        pullPolicy: ${PULL_POLICY:-IfNotPresent}

      ingress:
        enabled: ${INGRESS_ENABLED:-false}
        ingressClassName: ${INGRESS_CLASS_NAME:-nginx}
        hostname: ${VAULT_INGRESS_HOSTNAME}.${VAULT_INGRESS_DOMAIN}
        tls: true
        extraTls:
          - hosts:
            - ${VAULT_INGRESS_HOSTNAME}.${VAULT_INGRESS_DOMAIN}
        secretName: ${VAULT_INGRESS_HOSTNAME}.${VAULT_INGRESS_DOMAIN}

    global:
      storageClass: ${STORAGE_CLASS:-standard}
      security:
        allowInsecureImages: true

    injector:
      enabled: ${INJECTOR_ENABLED:-true}
      serviceAccount:
        automountServiceAccountToken: true
      image:
        registry: ${REGISTRY:-ghcr.io}
        repository: ${INJECTOR_REPOSITORY:-stuttgart-things/vault-k8s}
        tag: ${INJECTOR_TAG:-1.7.0-debian-12-r4}
        pullPolicy: ${INJECTOR_PULL_POLICY:-IfNotPresent}

    volumePermissions:
      enabled: ${ENABLE_VOLUME_PERMISSIONS:-true}
      image:
        registry: ${REGISTRY:-ghcr.io}
        repository: ${OS_SHELL_REPOSITORY:-stuttgart-things/os-shell}
        tag: ${OS_SHELL_TAG:-12-debian-12-r50}
        digest: ""
        pullPolicy: ${OS_SHELL_PULL_POLICY:-IfNotPresent}